---
TQDM_DISABLE: True

DEVICE: "cpu"

STRATEGY: "fedavg"

NUM_ROUNDS: 1
NUM_EPOCHS: 5

BATCH_SIZE: 32
VAL_RATIO: 0.2
SEED: 42

PROXIMAL_MU: 0.0
client_optim_name: "sgd"
client_optim_args:
  lr: 0.01
server_optim_name: "sgd"
server_optim_args:
  eta: 1e-2
  beta_1: 0.9
  beta_2: 0.99
  tau: 1e-3

NUM_CLIENTS: 10
IID: False
STRAGGLERS_FRACTION: 0.0

SAVE_PATH: "docs/results/distributed"
