---
TQDM_DISABLE: False

DEVICE: "cuda"

NUM_ROUNDS: 1
NUM_EPOCHS: 5

BATCH_SIZE: 32
VAL_RATIO: 0.2
SEED: 42

PROXIMAL_MU: 0.0
optim_name: "sgd"
optim_args:
  lr: 0.001

SAVE_PATH: "docs/results/centralized"
